version: "3.9"

services:
  mariadb:
    image: mariadb:10.9
    container_name: mariadb_local
    restart: always
    environment:
      TZ: America/Bogota
      MARIADB_ROOT_PASSWORD: YhYE9B5pVd
      MARIADB_DATABASE: u146022362_QGqUq
      MARIADB_USER: u146022362_FPpam
      MARIADB_PASSWORD: YhYE9B5pVd
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
