name: Nest CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Typecheck
        run: yarn tsc --noEmit -p tsconfig.build.json

      - name: Unit tests
        run: yarn test --passWithNoTests --ci
